version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: the_wild_oasis_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_secure # Please change this
      MYSQL_DATABASE: the_wild_oasis_db
      MYSQL_USER: oasis_user
      MYSQL_PASSWORD: password_oasis # Please change this
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: